In [13]:
# read data
rm(list = ls()) #ワークスメモリをクリア
data01 <- read.csv('./exc_data//data01.csv') # csv読み込み
data01 #　行x列サイズも表示される
head(data01)
summary(data01)

x1 y1
1 63 63
2 56 66
3 51 61
4 50 60
5 42 52

x1 y1
1 63 63
2 56 66
3 51 61
4 50 60
5 42 52

       x1             y1      
 Min.   :42.0   Min.   :52.0  
 1st Qu.:50.0   1st Qu.:60.0  
 Median :51.0   Median :61.0  
 Mean   :52.4   Mean   :60.4  
 3rd Qu.:56.0   3rd Qu.:63.0  
 Max.   :63.0   Max.   :66.0  

In [14]:
# 手打ちでやりたいときはこれ
x1 <- c(63, 56, 51, 50)
y1 <- c(56, 51, 50, 63)
df1 <- data.frame(x1, y1)
df1

x1 y1
1 63 56
2 56 51
3 51 50
4 50 63

In [19]:
data01[3, ] # 1x2
data01[ , 2] # 5x1が[要素5個]のリスト的に出てくる
data01[3, 2]

x1 y1
3 51 61

[1] 63 66 61 60 52

[1] 61

In [21]:
mean(data01$x1) # ${変数名}で統計量をみる対象の変数を指定
mean(data01$y1)

[1] 52.4

[1] 60.4

In [28]:
# forループ練習
output <- matrix(NA, 2, 2) # matrix(data, nrow, ncol, [options]))
tmp <- matrix(1:6, 3)
output
tmp

# forでmean, sdだす
for (j in 1:2){
    output[j, 1] <- mean(data01[, j]) # 列ごとの平均値
    output[j, 2] <- sd(data01[, j]) #列ごとの標準偏差
}
output            

# 上はこれと同じ
apply(data01, 2, mean)
apply(data01, 2, sd)

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]    
[1,] 52.4 7.765307
[2,] 60.4 5.224940

x1   y1 
52.4 60.4

x1       y1 
7.765307 5.224940